### PR TITLE
Adding two ABRACON SMD crystals (part two)

### PR DESCRIPTION
**Pull request by zeroping**
Continuing from https://github.com/KiCad/Crystals_Oscillators_SMD.pretty/pull/3#issuecomment-139927661

If my understanding of the KLC and your suggestions is right, then these should be fixed now. An experienced eye is probably the best checking tool, so please take a look at them anyways.

### CODE REVIEW

**Comment by pointhi** [comment]
Please apply KLC:

```
checking module: Crystal_SMD_ABM3C
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
checking module: Crystal_SMD_ABM8G
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
```

Please also note crystals have wider clearances than other footprints:

```
6.7. Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and crystals at 0.5mm and BGA at 1.0mm. (IPC-7251, IPC-7351B)
```

**Comment by jkriege2** [comment]
should be fixed by this PR: https://github.com/KiCad/Crystals.pretty/pull/19

**Comment by jkriege2** [comment]
is included in this: https://github.com/KiCad/Crystals.pretty/pull/19

**Comment by zeroping** [comment]
It looks like you included the two parts I had wanted to, the ABM3C and the ABM8. Good job on getting both the ABM3C and the ABM3B - they're nearly identical but slightly different. Thanks for being more awesome than I have been!

 Fixed as soon as #19 goes in.

**Pull request closed without merging**
