### PR TITLE
2520 crystal

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.txccrystal.com/images/pdf/8z-accuracy.pdf

### CODE REVIEW

**Comment by pointhi** [comment]
Please look onto the schematic symbol of the crystal with gnd plane, and adjust the pin definition accordingly

**Comment by SchrodingersGat** [comment]
untitled

Adjusted

**Comment by pointhi** [comment]
please note the courtjard has to have a distance of 0,5mm for crystals

the rest looks fine to me

**Comment by SchrodingersGat** [comment]
Done

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
