### PR TITLE
Five new footprints of Epson 32.768 kHz crystal oscillators.

### PR DESCRIPTION
**Pull request by anpaza**
Here are five new footprints for Epson clock crystals.
The footprints were made by Epson guidelines.
The URL to the respective docs are in the desc field.
Also there's a matching pull request for kicad-library which adds five 3D models of these crystals.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @anpaza  thanks for contributing these. A few things to note:
- Have a look through the library conventions file - https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt and make sure you run your footprints through the checker script - https://github.com/KiCad/kicad-library-utils
- You shouldn't have any silkscreen placed over the pads - use the F.Fab layer to designate component outline, and place silkscreen only where it will be visible after the component has been placed on the PCB.
- The courtyard clearance for crystals should be 0.5mm, so please increase this
- Please place the component name where it is not obscured by the pads
- For crystals, there is a running convention to determine pad numbering. Label the two crystal inputs 1 and 2, any ground pins 3, and non-connected pins have a blank number field. For example MC_146 and MC_156, please change pin "4" to "2", and change "2" and "3" to blank numbering). **This is done so that the footprints match the crystal symbols in device.lib**
- Please add "Crystal_" to the start of each filename, to match the other filenames in the repository (ignoring the HC crystals which need to get fixed)

Thanks, hopefully we can get these merged soon!

**Comment by SchrodingersGat** [comment]
Check out https://github.com/KiCad/Crystals.pretty/pull/5 which touches a few of these issues

**Comment by anpaza** [comment]
Thank you for your comments. Of course I have read the KLC :) but you clarified some points that were fuzzy to me before.
I have modified the components. Should I create a new pull request or I can add somehow the new commits to this existing request?

**Comment by SchrodingersGat** [comment]
The recent changes automatically show up here. Thanks for these, they look good.

**Comment by anpaza** [comment]
Thank you.
How about the 3D models?
https://github.com/KiCad/kicad-library/pull/540
are there any guidelines I should follow, like KLC3D?

**Pull request merged**
