### PR TITLE
updated library to meet KLC requirements and added several crystals/resonators

### PR DESCRIPTION
**Pull request by jkriege2**
- based on scripts: https://github.com/pointhi/kicad-footprint-generator/pull/17
- PR to rename 3D models and modify FPFilters: https://github.com/KiCad/kicad-library/pull/868
- fixed all KLC issues (all footprints check out with new script versions!)
- added many packages and different styles for packages
- support existing 3d models

Screenshots show most (but not all variants!) of the new/updated footprints:
c_tht1
c_tht2

crystal_all
crystal_silk
crystal_smd
c_tht

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 this is a **huge** effort! Well done.

I would like to see some consistency with regard to naming convention.

### Package Size
The package size is currently designated as (e.g.)

* `l10.0mm_d3.0mm`
* `package6.0x3.6mm`
* `w10mm_h5mm`

I would suggest simply using (e.g.) `_5.0x3.2mm` without any extra words e.g. "package".

### Pin Count
Also, sometimes you specify pin-count before package size, and sometimes after. Please use the same convention for all!

Great work otherwise :)

**Comment by jkriege2** [comment]
OK,
the names are more consistent now:
1. all SMD-footrpints use the for `-**P**pin_**W**x**h**mm`
2. THT footprints have either non sizes (standard packages, as e.g. HC49), or use a combination of the forms `_w**W**mm` `_h**H**mm` `_d**D**mm` `_l**L**mm`. This is necessary to accomodate the different measure of a (generally) not-rectangular package ... e.g. for round it would not be really clear whether `3x10mm` is 3mm diameter and 10mm length, or vice-versa ... 

Anything else?

Best,
JAN

PS: 3D packages have been renamed and some more round 3D models were added (see https://github.com/KiCad/kicad-library/pull/868)

**Comment by jkriege2** [comment]
Hi!

if you have time: please also review these, as they are connected (Oscillators, but use the same scripts!):
- https://github.com/KiCad/Oscillators.pretty/pull/4
- https://github.com/KiCad/kicad-library/pull/814

Best & Thanks,
JAN

**Comment by SchrodingersGat** [comment]
Fantastic work once again.

Browsing through these I see a couple of 3D models that are misalinged:

### Crystal_HC33_U_Vertical
crystal_hc33_u_vertical

### Crystal_SMD_5032_4Pin_5.0x3.2mm
crystal_smd_5032_4pin_5 0x3 2mm

Apart from that it looks very good.

**Comment by jkriege2** [comment]
Hi!

I updated the footprints again and fixed those issues (also by adding new 3D models, see: https://github.com/KiCad/kicad-library/pull/868)

Ready to merge?

cu
JAN

2017-01-12 15_21_51-3d viewer
2017-01-12 15_24_08-3d viewer

**Comment by SchrodingersGat** [comment]
Yep I think we are good to go. Fantastic :)

**Pull request merged**
