### PR TITLE
Add a footprint for FC-135 SMD crystal

### PR DESCRIPTION
**Pull request by dingari**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work ... please change a few things:
1. please rename the crystal to match the scheme of the other crystals, e.g.  `Crystal_SMD_SeikoEpson_FC135-2pin_3.2x1.5mm`
2. courtyard offset should be 0.25mm from the outline of the pads (i.e. ~0.1mm smaller than in your footprint)
3. Please add a text `%R`on F.Fab (overlay with REFDES), this replicates REFDES on F.Fab (new KLC rule ;-)

Best,
JAN

**Comment by dingari** [comment]
Hi, I've fixed those issues.

One thing: You say that the courtyard should be 0.25mm from the pads. but rule 6.7 from the KLC says:

>Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and **crystals at 0.5mm** and BGA at 1.0mm. (IPC-7251, IPC-7351B)

Are there changes to KLC that have yet to be updated in the wiki?

**Comment by jkriege2** [comment]
THe question is from where you measure courtyard. The idea is: ignore silkscreen and take the outline (on F.Fab) and the different pads. always take what's further out. See examplemimages here: https://github.com/SchrodingersGat/kicad-library/wiki/KLC

**Comment by dingari** [comment]
Yep, I get that. I was totally putting the courtyard 0.5mm from the component outline, not the outline of the pads.

My question however, was why the KLC says 0.5mm, when you say 0.25mm (which I agree is much better).

Anyways, I think this can be merged now :)

**Comment by jkriege2** [comment]
Aahhh ... I overread the fat part ... sorry ... I'll get back to you on that!

JAN

**Comment by dingari** [comment]
Hi, I'm now realizing that this is essentially a 3215 (3.2 x 1.5mm) crystal footprint. Maybe it would make more sense to rename it a s such to be consistent with the others?

See: http://www.mecxtal-europe.com/x3215-1.pdf

**Comment by jkriege2** [comment]
yes, I think that would be a great idea!
JAN

PS: Please orient the name on one of the existing footprints, e.g. `Crystal_SMD_5032-2pin_5.0x3.2mm`

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
