### PR TITLE
Added Crystal_SMD_5032_4Pads

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Passes KLC
- 3D model also

5032_4pads

Example of this footprint - http://www.abracon.com/Resonators/abm3b.pdf

3D model is here: https://github.com/KiCad/kicad-library/pull/426

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
5032_2pads

3D model for the Crystal_SMD_5032_2Pads also added

**Comment by pointhi** [comment]
Please look onto the schematic symbol of the crystal with the gnd plane, and adjust the pin definition accordingly. For example, look onto #4 how the pins have to be arange, to be able to work with the schematic symbol.

**Comment by SchrodingersGat** [comment]
untitled

@pointhi is this what you mean?

**Comment by pointhi** [comment]
yep, otherwise schematic and footprint wouldn't work together by default

**Comment by SchrodingersGat** [comment]
Yep, I had a 4-pin schematic symbol which matched the manufacturers pin numbering. But this is consistent. Consistent is good.

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
