### PR TITLE
added Crystal_SMD_Micro-Crystal_MS1V-T1K.kicad_mod tuning fork

### PR DESCRIPTION
**Pull request by feichtinger**
bildschirmfoto vom 2016-10-26 00-32-01

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi (again)!

two things on that one:
1. Could you move the anchor to the center of the component (center between the pins)? 
2. A suggestion from me (not necessary and I will merge without it, if you don't like): May I suggest to also draw the leads onto the FAB? I think the symbol gets clearer then: 
crys

Best,
JAN

**Comment by feichtinger** [comment]
> 1. Could you move the anchor to the center of the component (center between the pins)? 

I know about this rule but in this case I found it hard to define a "center of component" so I have chosen the bottom of the metal can. Do you mean this way?
bildschirmfoto vom 2016-10-26 11-28-23

> May I suggest to also draw the leads onto the FAB? I think the symbol gets clearer then.

Yes, that's a good idea. Fixed it.

**Comment by jkriege2** [comment]
ad 1) No the center is in the center of the pads ... I think the python-scripts to check KLC can move the component if you provide the --fix option ... Basically the center should be on the hieght of pad 3 and somewhere on the half distance between pins 1/2 and pin 3

cu
JAN

**Comment by jkriege2** [comment]
... see e.g. a SOT-23 package?

**Comment by feichtinger** [comment]
OK

**Comment by jkriege2** [comment]
Great!

thanks,
JAN

**Pull request merged**
