### PR TITLE
add ABM3B

### PR DESCRIPTION
**Pull request by pointhi**
abm3b

We should also rename `ABM3.kicad_mod` to `Crystal_SMD_ABM3.kicad_mod`

### CODE REVIEW

**Comment by michal777** [comment]
Can the way of using F.Fab layer be defined in KLC? Would be nice to set some rules. Marking the pin 1 would make it more useful as documentation layer. Should it be accurate outline or something simplified (IPC7351/7251)? Also would be lovely to have designators inside (text %R, shown or hidden?).

**Comment by CarlPoirier** [comment]
@michal777 Let's open an issue and discuss the KLC there.

Edit: Here it is: https://github.com/KiCad/kicad-library/issues/409

**Comment by pointhi** [comment]
@CarlPoirier bump

**Comment by CarlPoirier** [comment]
Sounds good to me, thanks!

**Pull request merged**
