### PR TITLE
adding Abracon ABM3 SMD crsytal footprint

### PR DESCRIPTION
**Pull request by hyOzd**
This is the footprint for Abracon's ABM3 series SMD crystal. It's designed according to datasheet linked below.

http://www.abracon.com/Resonators/abm3.pdf

### CODE REVIEW

**Comment by pointhi** [comment]
Please apply KLC:

```
checking module: ABM3
  Violating Rule 10.3
    Keywords are separated by spaces.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

Please also note crystals have wider clearances than other footprints:

```
6.7. Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and crystals at 0.5mm and BGA at 1.0mm. (IPC-7251, IPC-7351B)
```

**Comment by hyOzd** [comment]
All violations are fixed.

**Comment by pointhi** [comment]
Hy,
- for me, the height which is represented by the silk screen seems a little bit to big. (currently, the silk screen represents a crystal in the size of about  `5.0x3.8` and not `5.0x3.2`). Please note to adjust the courtjard in y-size after changing the silkscreen.
- also consider, the reference text is normaly placed on top of the footprint, and the value text at the bottom.

The rest seems fine for me.

**Comment by hyOzd** [comment]
Thanks for suggestions. I've just uploaded a new revision.

I've placed silkscreen just to the edge. Component has a max size of `5.0x3.2`, so I placed silk screen at `5.2x3.4`. With a width of `0.15` it should be still visible. I hope this is okay.

**Comment by pointhi** [comment]
Yep, that's okay.

One last proposal would be increasing the spacing between the pad and the silkscreen a little bit. (About 0.1-0.2 mm).
Personally, I'm using the default soldermask visible on the 3D-View as reference point where the silkscreen should approximately end.

**Comment by hyOzd** [comment]
In this case silk screen lines on the sides become tiny. See upper-left corner in below screenshot. In case of a low quality silkscreen they won't be noticable. Do you think I should slightly increase the size of silkscreen rectangle? Say `5.4x3.6`? Or maybe I should simply remove those, and just keep 2 horizontal lines.

screenshot from 2016-02-06 20 08 04

**Comment by pointhi** [comment]
I think it's enought to change the Y end of the silk screen from `1,3` to `1,4` (which would have the same effect as drawing it 0.2 mm wider and copping 0.2 on every side).

**Comment by hyOzd** [comment]
Ok, done.

**Comment by pointhi** [comment]
thanks for your work.

**Pull request merged**
