### PR TITLE
Crystal_SMD_3225_4Pads.kicad_mod: Introduce 4 Pads crystal 3.20x2.50mm

### PR DESCRIPTION
**Pull request by oliviermartin**
Support crystal such as SMD TXC sealing crystal:
http://www.txccrystal.com/images/pdf/7m-accuracy.pdf

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work, up to two things:
1. Could you move the silkscreen OUTSIDE the package, so it is visible after assembly (KLC 6.5)?
2. Could you please change the line width of the outline of the F.Fab layer to 0.10mm (KLC6.9)

Best,
JAN

PS: for KLCs see https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

**Comment by oliviermartin** [comment]
Hi Jan,
I addressed KLC6.9. I also changed the silkscreen outline 0.12mm (KLC6.5).
But I am not sure to understand what to do with KLC6.5 related to your comment.

Here is the my crystal footprint with the latest changes:
crystal

**Comment by jkriege2** [comment]
Hi!

I think I had the feeling that the silkscreen was below the actual component ... There is one thing about the SLK width: Usually we use 0.15mm, althought the KLC state 0.12mm ... I'm currently checking with the other maintainers, as we also have check scripts that require 0.15mm at the moment while the KLC state 0.12mm ... I'll let you know which one to take, when I get some answers ;-)

Otherwise the component looks good to me!

Best & Thanks already, JAN

**Comment by jkriege2** [comment]
Since there was no answer so far ... I would suggest changing the width to 0.15mm, as that's doen this way in all other footprints ;-)

Could you do that?
Thanks,
JAN

**Comment by jkriege2** [comment]
is included in this: https://github.com/KiCad/Crystals.pretty/pull/19

**Comment by evanshultz** [comment]
@jkriege2 Can this PR be closed then?

**Comment by jkriege2** [comment]
is included in this: #19

**Pull request closed without merging**
