### PR TITLE
Add a package SMD7050 with 4 pads

### PR DESCRIPTION
**Pull request by eldarkg**
[Link to details to the footprint](http://docs-europe.electrocomponents.com/webdocs/0d5a/0900766b80d5a3cd.pdf)
fp

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @eldarkg thanks for your contribution. A couple of suggestion here:

a) As there are a few different ways in which manufacturers designate pinouts for these crystals, we're trying to follow a standard so that all crystal footprints can be used interchangably with the same schematic symbol.

> Pins 1 & 2 are the oscillator inputs
> All GND pins are designated PIN3

e.g. https://github.com/KiCad/Crystals.pretty/pull/4
e.g. https://github.com/KiCad/Crystals.pretty/pull/7
e.g. https://github.com/KiCad/Crystals.pretty/pull/5

b) Please mark the simplified package outline on the F.Fab layer (as per the examples above)

Cheers

**Comment by eldarkg** [comment]
Fixed
fixed

**Comment by SchrodingersGat** [comment]
Thanks for your contribution :)

**Comment by diggit** [comment]
Hi @SchrodingersGat. Shouldn't be Courtyard around pads and not crossing them? I am not much familiar with FP yet, but...
- 6. Courtyard line has a width 0.05mm. This line is placed so that its **clearance is measured from its center to the edges of pads and body**, and its position is rounded on a grid of 0.05mm.

**Comment by eldarkg** [comment]
@diggit The courtyard it is grey line around the footprint on the my screenshoot

**Comment by diggit** [comment]
@eldarkg aah, thanks. I realized it few moments ago and hurried to delete my comment, too late. :D

**Pull request merged**
